version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: /myapp/docker/username
    DOCKER_PASS: /myapp/docker/password
    DOCKER_URL: /myapp/docker/url

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r day-14/simple-python-app/requirements.txt
  build:
    commands:
      - cd day-14/simple-python-app/
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_URL"
      - echo "Building Docker Image"
      - docker build -t "$DOCKER_URL/$DOCKER_USERNAME/flask-app1:latest" .
      - docker push "$DOCKER_URL/$DOCKER_USERNAME/flask-app1:latest"
  post_build:
    commands:
      - echo "Build is Successful"
      
artifacts:
  files:
    - appspec.yml
    - scripts/**/* 
    - day-14/**/* 
  base-directory: .
